mysql:
    image: mysql:5.7
    ports:
      - "33061:3306"
    volumes:
      - ./data:/var/lib/mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
    environment:
      - MYSQL_DATABASE=gao_kao
      - MYSQL_ROOT_PASSWORD=mysql
    restart: always